### ISSUE TITLE
Suggestion: use `main` for base_branch

### ISSUE THREAD

**Issue by leviable** [notsatan/go-template#25]
Gentle suggestion to use `main` for default base_branch instead of `master`.

Avoiding the broader debate about the reasons for and utility of the name change, the industry is trending in the direction of using `main` as the default base branch, and is arguably beyond the critical mass of adoption necessary. The major players in the space (GitHub, Gitlab) and associated tooling have already or will soon be switching to `main`, and as a related tool `go-template` might be best served by adopting that change now.

**Comment by notsatan** [comment]
Closing this issue for now. 

Though if you or anyone is interested to work on this (reading the value of `init.defaultBranch` and using that as the default value for `base_branch`), I would gladly appreciate the help!
