### ISSUE TITLE
Ran into exception while running validator: `is_module_hosted_on_github`

### ISSUE THREAD

**Issue by hmthanh** [notsatan/go-template#46]
Ran into exception while running validator: `is_module_hosted_on_github`
Stacktrace: `ValueError: Attempt to enable Github-specific features when module path does not belong to github`
 
go-template is still under development, if you feel that the error is incorrect, you are encouraged to raise an issue at: 
        https://github.com/notsatan/go-template

ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 246)

**Comment by notsatan** [comment]
Hi @hmthanh, given that you've closed the issue on Github I'll assume you're no longer running into this error and that `go-template` is working as expected!

If this is not the case (and you happened to close this issue by mistake), feel free to re-open this issue — note that I'll need the input parameters you used that lead to this issue.
