### ISSUE TITLE
Ran into exception while running validator: `is_module_hosted_on_github`

### ISSUE THREAD

**Issue by HaveF** [notsatan/go-template#53]
Hi!

Thanks for your repo!
The first time I try it failed. Don't know why

```
╰─$ cookiecutter gh:notsatan/go-template
You've downloaded /Users/mac/.cookiecutters/go-template before. Is it okay to delete and re-download it? [y/n] (y):
  [1/12] project_name (example-project): sqlite_saver_go
  [2/12] project_description (SqliteSaverGo is a Go application created using https://github.com/notsatan/go-template):
  [3/12] go_module_path (github.com/example/sqlite_saver_go): github.com/HaveF/sqlite_saver_go
  [4/12] license_owner (example): havef
  [5/12] base_branch (master): main
  [6/12] contact_email ():
  [7/12] github_specific_features (y):
  [8/12] private_project (n): y
  [9/12] use_codecov (y):
  [10/12] use_precommit (y):
  [11/12] Select go_version
    1 - 1.21
    2 - 1.20
    3 - 1.19
    Choose from [1/2/3] (1):
  [12/12] Select license
    1 - MIT
    2 - BSD-3
    3 - GNU GPL v3.0
    4 - Apache Software License 2.0
    Choose from [1/2/3/4] (1):


Ran into exception while running validator: `is_module_hosted_on_github`
Stacktrace: `ValueError: Attempt to enable Github-specific features when module path does not belong to github`


go-template is still under development, if you feel that the error is incorrect, you are encouraged to raise an issue at:
	https://github.com/notsatan/go-template

ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 246)
```

I also checked the issues, but without luck.

Thanks for your help again!

**Comment by notsatan** [comment]
Hi, thanks for reaching out. The issue seems to be with the regex pattern being used — it is not expecting an underscore

https://github.com/notsatan/go-template/blob/e146f9e1dd6951a53cfb1306897df407b354852a/hooks/pre_gen_project.py#L13-L14

Seems to be a bug — the regex should also allow for underscores in user/repository names since they are valid on Github. Will verify and push a fix if needed!

**Comment by notsatan** [comment]
This is indeed a bug. Since I am already making changes to the regex, should be able to simplify the pattern to

```regex
^github.com\/[\w\-]+\/[\w\-]+\/?$
```

**Comment by notsatan** [comment]
Should be fixed with this push. You can go through the same steps again to generate a new project — make sure you answer "*Is it okay to delete and re-download*" with a yes (that's the default)

Let me know how it goes!

**Comment by HaveF** [comment]
@notsatan nice! it works now 🎉🎉🎉

**Comment by HaveF** [comment]
@notsatan another small issue:

prompt message:
```
7) Upload initial code to git:
    $ git add -a
    $ git commit -m "Initial commit!"
    $ git remote add origin https://github.com/HaveF/sqlite_saver_go.git
    $ git push -u origin --all

If you have any suggestions, or encounter any issue, please raise an issue;
    https://github.com/notsatan/go-template
```

`git commit -m "Initial commit!"` should be `git commit -m 'Initial commit!'`

double quotes would have problem, like this:

![image](https://github.com/notsatan/go-template/assets/54462/f601ec46-8b70-4efc-82dc-29849a8307c5)

I use zsh in Mac, gpt says it also effect the bash, I don't know. Maybe Use Single Quotes is a good choice

**Comment by notsatan** [comment]
Not sure about the single/double quotes — double quote works on my end, default Mac and the original Linux system I tested it on. Will leave it as is for now, hopefully users with other shell(s) will be able to switch as needed

I'll look into modifying the instructions printed in case this becomes a more widespread issue. Thanks for the heads up!
